<?php
$z[0]=Array("field","",56,84);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",86,115);
$z[1][4]['name']="typename";
$z[2]=Array("field","",181,209);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n                        <li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title\r\n                            /]</a></li>\r\n                        ",326,571);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";

?>